# Generated by Django 3.0.8 on 2020-07-26 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200724_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('bid_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=7)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('bid_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auctions.Listing')),
            ],
        ),
    ]
