# Generated by Django 3.0.8 on 2020-07-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200729_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
