# Generated by Django 3.0.8 on 2020-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_price_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
