# Generated by Django 3.0.8 on 2020-08-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bids_bid_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_price_currency',
            field=models.CharField(blank=True, default=('en_GB', 'cp1252'), max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_currency',
            field=models.CharField(blank=True, default=('en_GB', 'cp1252'), max_length=3, null=True),
        ),
    ]
